import type { CourseApi } from "../types/student";

/**
 * Mock de materias completas con todos los datos de CourseApi
 * Basado en el plan de estudios de Ingeniería en Informática - FIUBA
 */

export const mockCourseApi: CourseApi[] = [
  // ============ PRIMER AÑO - PRIMER CUATRIMESTRE ============
  {
    id: "61.03",
    name: "Análisis Matemático I",
    category: "Matemática",
    schedules: [
      { day: "Lunes", startTime: "19:00", endTime: "22:00" },
      { day: "Jueves", startTime: "19:00", endTime: "22:00" },
    ],
    requiredCourses: [],
    year: 1,
    semester: "Primer Cuatrimestre",
    difficulty: "Medium",
    credits: 6,
  },
  {
    id: "62.01",
    name: "Física I",
    category: "Sistemas",
    schedules: [
      { day: "Martes", startTime: "18:00", endTime: "21:00" },
      { day: "Viernes", startTime: "18:00", endTime: "21:00" },
    ],
    requiredCourses: [],
    year: 1,
    semester: "Primer Cuatrimestre",
    difficulty: "Hard",
    credits: 6,
  },
  {
    id: "75.01",
    name: "Álgebra y Geometría Analítica",
    category: "Matemática",
    schedules: [
      { day: "Miércoles", startTime: "19:00", endTime: "22:00" },
      { day: "Sábado", startTime: "09:00", endTime: "12:00" },
    ],
    requiredCourses: [],
    year: 1,
    semester: "Primer Cuatrimestre",
    difficulty: "Medium",
    credits: 6,
  },
  {
    id: "75.40",
    name: "Algoritmos y Programación I",
    category: "Programación",
    schedules: [
      { day: "Lunes", startTime: "18:00", endTime: "21:00" },
      { day: "Miércoles", startTime: "18:00", endTime: "21:00" },
    ],
    requiredCourses: [],
    year: 1,
    semester: "Primer Cuatrimestre",
    difficulty: "Easy",
    credits: 6,
  },
  {
    id: "95.01",
    name: "Química",
    category: "Sistemas",
    schedules: [
      { day: "Martes", startTime: "19:00", endTime: "22:00" },
    ],
    requiredCourses: [],
    year: 1,
    semester: "Primer Cuatrimestre",
    difficulty: "Medium",
    credits: 4,
  },

  // ============ PRIMER AÑO - SEGUNDO CUATRIMESTRE ============
  {
    id: "61.08",
    name: "Análisis Matemático II",
    category: "Matemática",
    schedules: [
      { day: "Lunes", startTime: "19:00", endTime: "22:00" },
      { day: "Jueves", startTime: "19:00", endTime: "22:00" },
    ],
    requiredCourses: ["61.03"],
    year: 1,
    semester: "Segundo Cuatrimestre",
    difficulty: "Hard",
    credits: 6,
  },
  {
    id: "62.03",
    name: "Física II",
    category: "Sistemas",
    schedules: [
      { day: "Martes", startTime: "18:00", endTime: "21:00" },
      { day: "Viernes", startTime: "18:00", endTime: "21:00" },
    ],
    requiredCourses: ["62.01", "61.03"],
    year: 1,
    semester: "Segundo Cuatrimestre",
    difficulty: "Hard",
    credits: 6,
  },
  {
    id: "75.02",
    name: "Análisis Numérico I",
    category: "Matemática",
    schedules: [
      { day: "Miércoles", startTime: "19:00", endTime: "22:00" },
    ],
    requiredCourses: ["75.01", "75.40"],
    year: 1,
    semester: "Segundo Cuatrimestre",
    difficulty: "Medium",
    credits: 4,
  },
  {
    id: "75.41",
    name: "Algoritmos y Programación II",
    category: "Programación",
    schedules: [
      { day: "Lunes", startTime: "18:00", endTime: "21:00" },
      { day: "Jueves", startTime: "18:00", endTime: "21:00" },
    ],
    requiredCourses: ["75.40"],
    year: 1,
    semester: "Segundo Cuatrimestre",
    difficulty: "Easy",
    credits: 6,
  },

  // ============ SEGUNDO AÑO - PRIMER CUATRIMESTRE ============
  {
    id: "61.09",
    name: "Probabilidad y Estadística",
    category: "Matemática",
    schedules: [
      { day: "Miércoles", startTime: "19:00", endTime: "22:00" },
      { day: "Viernes", startTime: "19:00", endTime: "22:00" },
    ],
    requiredCourses: ["61.08"],
    year: 2,
    semester: "Primer Cuatrimestre",
    difficulty: "Medium",
    credits: 6,
  },
  {
    id: "66.20",
    name: "Arquitectura de Computadoras",
    category: "Arquitectura",
    schedules: [
      { day: "Lunes", startTime: "20:00", endTime: "23:00" },
      { day: "Miércoles", startTime: "20:00", endTime: "23:00" },
    ],
    requiredCourses: ["62.03"],
    year: 2,
    semester: "Primer Cuatrimestre",
    difficulty: "Medium",
    credits: 6,
  },
  {
    id: "75.03",
    name: "Análisis Numérico II",
    category: "Matemática",
    schedules: [
      { day: "Martes", startTime: "19:00", endTime: "22:00" },
    ],
    requiredCourses: ["75.02"],
    year: 2,
    semester: "Primer Cuatrimestre",
    difficulty: "Hard",
    credits: 4,
  },
  {
    id: "75.07",
    name: "Algoritmos y Programación III",
    category: "Programación",
    schedules: [
      { day: "Lunes", startTime: "18:00", endTime: "21:00" },
      { day: "Jueves", startTime: "18:00", endTime: "21:00" },
    ],
    requiredCourses: ["75.41"],
    year: 2,
    semester: "Primer Cuatrimestre",
    difficulty: "Easy",
    credits: 6,
  },

  // ============ SEGUNDO AÑO - SEGUNDO CUATRIMESTRE ============
  {
    id: "71.14",
    name: "Modelos y Optimización I",
    category: "Gestión",
    schedules: [
      { day: "Viernes", startTime: "18:00", endTime: "21:00" },
    ],
    requiredCourses: ["61.08", "75.01"],
    year: 2,
    semester: "Segundo Cuatrimestre",
    difficulty: "Medium",
    credits: 4,
  },
  {
    id: "75.04",
    name: "Elementos de Teoría de Algoritmos",
    category: "Programación",
    schedules: [
      { day: "Martes", startTime: "19:00", endTime: "22:00" },
    ],
    requiredCourses: ["75.07"],
    year: 2,
    semester: "Segundo Cuatrimestre",
    difficulty: "Easy",
    credits: 4,
  },
  {
    id: "75.08",
    name: "Sistemas Operativos",
    category: "Sistemas",
    schedules: [
      { day: "Lunes", startTime: "19:00", endTime: "22:00" },
      { day: "Jueves", startTime: "19:00", endTime: "22:00" },
    ],
    requiredCourses: ["75.07"],
    year: 2,
    semester: "Segundo Cuatrimestre",
    difficulty: "Medium",
    credits: 6,
  },
  {
    id: "75.42",
    name: "Taller de Programación I",
    category: "Programación",
    schedules: [
      { day: "Miércoles", startTime: "18:00", endTime: "22:00" },
    ],
    requiredCourses: ["75.07"],
    year: 2,
    semester: "Segundo Cuatrimestre",
    difficulty: "Easy",
    credits: 4,
  },

  // ============ TERCER AÑO - PRIMER CUATRIMESTRE ============
  {
    id: "71.15",
    name: "Modelos y Optimización II",
    category: "Gestión",
    schedules: [
      { day: "Viernes", startTime: "18:00", endTime: "21:00" },
    ],
    requiredCourses: ["71.14"],
    year: 3,
    semester: "Primer Cuatrimestre",
    difficulty: "Hard",
    credits: 4,
  },
  {
    id: "75.09",
    name: "Análisis de la Información",
    category: "Gestión",
    schedules: [
      { day: "Martes", startTime: "19:00", endTime: "22:00" },
    ],
    requiredCourses: ["75.04"],
    year: 3,
    semester: "Primer Cuatrimestre",
    difficulty: "Easy",
    credits: 4,
  },
  {
    id: "75.12",
    name: "Organización de Datos",
    category: "Programación",
    schedules: [
      { day: "Lunes", startTime: "19:00", endTime: "22:00" },
      { day: "Miércoles", startTime: "19:00", endTime: "22:00" },
    ],
    requiredCourses: ["75.42", "61.09"],
    year: 3,
    semester: "Primer Cuatrimestre",
    difficulty: "Medium",
    credits: 6,
  },
  {
    id: "75.43",
    name: "Introducción a Sistemas Distribuidos",
    category: "Sistemas",
    schedules: [
      { day: "Jueves", startTime: "18:00", endTime: "21:00" },
    ],
    requiredCourses: ["75.08"],
    year: 3,
    semester: "Primer Cuatrimestre",
    difficulty: "Medium",
    credits: 4,
  },

  // ============ TERCER AÑO - SEGUNDO CUATRIMESTRE ============
  {
    id: "75.06",
    name: "Organización del Computador",
    category: "Arquitectura",
    schedules: [
      { day: "Martes", startTime: "20:00", endTime: "23:00" },
      { day: "Jueves", startTime: "20:00", endTime: "23:00" },
    ],
    requiredCourses: ["66.20"],
    year: 3,
    semester: "Segundo Cuatrimestre",
    difficulty: "Hard",
    credits: 6,
  },
  {
    id: "75.10",
    name: "Técnicas de Diseño de Algoritmos",
    category: "Programación",
    schedules: [
      { day: "Lunes", startTime: "19:00", endTime: "22:00" },
    ],
    requiredCourses: ["75.04"],
    year: 3,
    semester: "Segundo Cuatrimestre",
    difficulty: "Easy",
    credits: 4,
  },
  {
    id: "75.44",
    name: "Administración y Control de Proyectos I",
    category: "Gestión",
    schedules: [
      { day: "Miércoles", startTime: "18:00", endTime: "21:00" },
    ],
    requiredCourses: ["75.09"],
    year: 3,
    semester: "Segundo Cuatrimestre",
    difficulty: "Easy",
    credits: 4,
  },
  {
    id: "75.59",
    name: "Técnicas de Programación Concurrente",
    category: "Programación",
    schedules: [
      { day: "Viernes", startTime: "18:00", endTime: "21:00" },
    ],
    requiredCourses: ["75.08"],
    year: 3,
    semester: "Segundo Cuatrimestre",
    difficulty: "Medium",
    credits: 4,
  },

  // ============ CUARTO AÑO - PRIMER CUATRIMESTRE ============
  {
    id: "75.15",
    name: "Base de Datos",
    category: "Programación",
    schedules: [
      { day: "Lunes", startTime: "19:00", endTime: "22:00" },
      { day: "Miércoles", startTime: "19:00", endTime: "22:00" },
    ],
    requiredCourses: ["75.12"],
    year: 4,
    semester: "Primer Cuatrimestre",
    difficulty: "Medium",
    credits: 6,
  },
  {
    id: "75.28",
    name: "Lenguajes y Compiladores",
    category: "Programación",
    schedules: [
      { day: "Martes", startTime: "19:00", endTime: "22:00" },
    ],
    requiredCourses: ["75.10"],
    year: 4,
    semester: "Primer Cuatrimestre",
    difficulty: "Hard",
    credits: 4,
  },
  {
    id: "75.29",
    name: "Teoría de las Comunicaciones",
    category: "Sistemas",
    schedules: [
      { day: "Jueves", startTime: "18:00", endTime: "21:00" },
    ],
    requiredCourses: ["61.09", "62.03"],
    year: 4,
    semester: "Primer Cuatrimestre",
    difficulty: "Hard",
    credits: 4,
  },
  {
    id: "75.73",
    name: "Criptografía y Seguridad Informática",
    category: "Sistemas",
    schedules: [
      { day: "Viernes", startTime: "19:00", endTime: "22:00" },
    ],
    requiredCourses: ["75.08"],
    year: 4,
    semester: "Primer Cuatrimestre",
    difficulty: "Medium",
    credits: 4,
  },

  // ============ CUARTO AÑO - SEGUNDO CUATRIMESTRE ============
  {
    id: "75.31",
    name: "Ingeniería de Software",
    category: "Gestión",
    schedules: [
      { day: "Lunes", startTime: "18:00", endTime: "21:00" },
      { day: "Miércoles", startTime: "18:00", endTime: "21:00" },
    ],
    requiredCourses: ["75.44"],
    year: 4,
    semester: "Segundo Cuatrimestre",
    difficulty: "Easy",
    credits: 6,
  },
  {
    id: "75.47",
    name: "Taller de Desarrollo de Proyectos II",
    category: "Programación",
    schedules: [
      { day: "Martes", startTime: "18:00", endTime: "22:00" },
    ],
    requiredCourses: ["75.31"],
    year: 4,
    semester: "Segundo Cuatrimestre",
    difficulty: "Easy",
    credits: 4,
  },
  {
    id: "75.52",
    name: "Redes de Computadoras",
    category: "Sistemas",
    schedules: [
      { day: "Jueves", startTime: "19:00", endTime: "22:00" },
      { day: "Viernes", startTime: "19:00", endTime: "22:00" },
    ],
    requiredCourses: ["75.29", "75.43"],
    year: 4,
    semester: "Segundo Cuatrimestre",
    difficulty: "Medium",
    credits: 6,
  },

  // ============ QUINTO AÑO - PRIMER CUATRIMESTRE ============
  {
    id: "75.39",
    name: "Sistemas Gráficos",
    category: "Sistemas",
    schedules: [
      { day: "Lunes", startTime: "19:00", endTime: "22:00" },
    ],
    requiredCourses: ["75.06", "75.02"],
    year: 5,
    semester: "Primer Cuatrimestre",
    difficulty: "Medium",
    credits: 4,
  },
  {
    id: "75.74",
    name: "Administración de Recursos",
    category: "Gestión",
    schedules: [
      { day: "Miércoles", startTime: "18:00", endTime: "21:00" },
    ],
    requiredCourses: ["75.44"],
    year: 5,
    semester: "Primer Cuatrimestre",
    difficulty: "Easy",
    credits: 4,
  },

  // ============ QUINTO AÑO - SEGUNDO CUATRIMESTRE ============
  {
    id: "75.35",
    name: "Teoría de Lenguajes",
    category: "Programación",
    schedules: [
      { day: "Martes", startTime: "19:00", endTime: "22:00" },
    ],
    requiredCourses: ["75.28"],
    year: 5,
    semester: "Segundo Cuatrimestre",
    difficulty: "Hard",
    credits: 4,
  },
];
