import type { CourseCombination } from "../types/student";

/**
 * Datos de ejemplo para las combinaciones de materias
 *
 * Assumptions:
 * - Las combinaciones están pre-calculadas y priorizadas por el backend
 * - La prioridad se basa en: nivel de habilidades, disponibilidad laboral, y carga máxima
 * - Los horarios reflejan la modalidad de cursada típica de la FIUBA
 * - Las recomendaciones consideran la progresión natural del plan de estudios
 */

export const mockCourseCombinations: CourseCombination[] = [
  {
    id: "combo-1",
    priority: 1,
    totalHours: 18,
    compatibilityScore: 95,
    totalCredits: 16,
    overlapHours: 0,
    courses: [
      {
        id: "course-1",
        name: "Algoritmos y Programación II",
        category: "Programación",
        schedules: [
          { day: "Lunes", startTime: "19:00", endTime: "22:00" },
          { day: "Jueves", startTime: "19:00", endTime: "22:00" },
        ],
        requiredCourses: ["course-0"],
        year: 1,
        semester: "Segundo Cuatrimestre",
        difficulty: "Easy",
        credits: 6,
      },
      {
        id: "course-2",
        name: "Organización de Datos",
        category: "Programación",
        schedules: [
          { day: "Martes", startTime: "19:00", endTime: "22:00" },
          { day: "Viernes", startTime: "19:00", endTime: "22:00" },
        ],
        requiredCourses: ["course-1"],
        year: 3,
        semester: "Primer Cuatrimestre",
        difficulty: "Medium",
        credits: 6,
      },
      {
        id: "course-3",
        name: "Probabilidad y Estadística",
        category: "Matemática",
        schedules: [{ day: "Miércoles", startTime: "19:00", endTime: "22:00" }],
        requiredCourses: [],
        year: 2,
        semester: "Primer Cuatrimestre",
        difficulty: "Medium",
        credits: 4,
      },
    ],
    coursesMetadata: {
      "course-1": { isRecommended: true },
      "course-2": { isRecommended: true },
    },
  },
  {
    id: "combo-2",
    priority: 2,
    totalHours: 21,
    compatibilityScore: 88,
    totalCredits: 20,
    overlapHours: 0,
    warnings: ["Carga horaria alta"],
    courses: [
      {
        id: "course-4",
        name: "Algoritmos y Programación III",
        category: "Programación",
        schedules: [
          { day: "Lunes", startTime: "18:00", endTime: "21:00" },
          { day: "Miércoles", startTime: "18:00", endTime: "21:00" },
        ],
        requiredCourses: ["course-1"],
        year: 2,
        semester: "Primer Cuatrimestre",
        difficulty: "Easy",
        credits: 6,
      },
      {
        id: "course-5",
        name: "Sistemas Operativos",
        category: "Sistemas",
        schedules: [
          { day: "Martes", startTime: "19:00", endTime: "22:00" },
          { day: "Jueves", startTime: "19:00", endTime: "22:00" },
        ],
        requiredCourses: ["course-4"],
        year: 2,
        semester: "Segundo Cuatrimestre",
        difficulty: "Medium",
        credits: 6,
      },
      {
        id: "course-6",
        name: "Gestión de Datos",
        category: "Gestión",
        schedules: [{ day: "Viernes", startTime: "18:00", endTime: "21:00" }],
        requiredCourses: [],
        year: 3,
        semester: "Primer Cuatrimestre",
        difficulty: "Easy",
        credits: 4,
      },
      {
        id: "course-7",
        name: "Análisis Matemático II",
        category: "Matemática",
        schedules: [{ day: "Sábado", startTime: "09:00", endTime: "12:00" }],
        requiredCourses: ["course-math-1"],
        year: 1,
        semester: "Segundo Cuatrimestre",
        difficulty: "Hard",
        credits: 6,
      },
    ],
    coursesMetadata: {
      "course-4": { isRecommended: true },
    },
  },
  {
    id: "combo-3",
    priority: 3,
    totalHours: 15,
    compatibilityScore: 82,
    totalCredits: 14,
    overlapHours: 0,
    warnings: ["Horarios nocturnos"],
    courses: [
      {
        id: "course-8",
        name: "Arquitectura de Computadoras",
        category: "Arquitectura",
        schedules: [
          { day: "Lunes", startTime: "20:00", endTime: "23:00" },
          { day: "Miércoles", startTime: "20:00", endTime: "23:00" },
        ],
        requiredCourses: [],
        year: 2,
        semester: "Primer Cuatrimestre",
        difficulty: "Medium",
        credits: 6,
      },
      {
        id: "course-9",
        name: "Teoría de Algoritmos",
        category: "Programación",
        schedules: [{ day: "Martes", startTime: "19:00", endTime: "22:00" }],
        requiredCourses: ["course-4"],
        year: 2,
        semester: "Segundo Cuatrimestre",
        difficulty: "Easy",
        credits: 4,
      },
      {
        id: "course-10",
        name: "Administración de Recursos",
        category: "Gestión",
        schedules: [{ day: "Jueves", startTime: "18:00", endTime: "21:00" }],
        requiredCourses: [],
        year: 5,
        semester: "Primer Cuatrimestre",
        difficulty: "Easy",
        credits: 4,
      },
    ],
    coursesMetadata: {
      "course-8": {
        hasTimeConflict: true,
        warnings: ["Horario nocturno tardío"],
      },
      "course-9": { isRecommended: true },
    },
  },
  {
    id: "combo-4",
    priority: 4,
    totalHours: 12,
    compatibilityScore: 78,
    totalCredits: 14,
    overlapHours: 0,
    courses: [
      {
        id: "course-11",
        name: "Métodos Numéricos",
        category: "Matemática",
        schedules: [{ day: "Lunes", startTime: "19:00", endTime: "22:00" }],
        requiredCourses: ["course-7"],
        year: 3,
        semester: "Primer Cuatrimestre",
        difficulty: "Hard",
        credits: 4,
      },
      {
        id: "course-12",
        name: "Diseño de Sistemas",
        category: "Sistemas",
        schedules: [{ day: "Miércoles", startTime: "19:00", endTime: "22:00" }],
        requiredCourses: ["course-5"],
        year: 3,
        semester: "Segundo Cuatrimestre",
        difficulty: "Medium",
        credits: 6,
      },
      {
        id: "course-13",
        name: "Modelos y Optimización I",
        category: "Gestión",
        schedules: [{ day: "Viernes", startTime: "19:00", endTime: "22:00" }],
        requiredCourses: [],
        year: 2,
        semester: "Segundo Cuatrimestre",
        difficulty: "Medium",
        credits: 4,
      },
    ],
  },
  {
    id: "combo-5",
    priority: 5,
    totalHours: 18,
    compatibilityScore: 75,
    totalCredits: 14,
    overlapHours: 2,
    warnings: ["Superposición de horarios"],
    courses: [
      {
        id: "course-14",
        name: "Redes de Computadoras",
        category: "Sistemas",
        schedules: [
          { day: "Martes", startTime: "18:00", endTime: "21:00" },
          { day: "Jueves", startTime: "18:00", endTime: "21:00" },
        ],
        requiredCourses: ["course-5"],
        year: 4,
        semester: "Segundo Cuatrimestre",
        difficulty: "Medium",
        credits: 6,
      },
      {
        id: "course-15",
        name: "Seguridad Informática",
        category: "Sistemas",
        schedules: [{ day: "Miércoles", startTime: "19:00", endTime: "22:00" }],
        requiredCourses: [],
        year: 4,
        semester: "Primer Cuatrimestre",
        difficulty: "Medium",
        credits: 4,
      },
      {
        id: "course-16",
        name: "Economía",
        category: "Gestión",
        schedules: [{ day: "Miércoles", startTime: "20:00", endTime: "22:00" }],
        requiredCourses: [],
        year: 3,
        semester: "Segundo Cuatrimestre",
        difficulty: "Easy",
        credits: 4,
      },
    ],
    coursesMetadata: {
      "course-15": { hasTimeConflict: true },
      "course-16": {
        hasTimeConflict: true,
        warnings: ["Superposición parcial con Seguridad Informática"],
      },
    },
  },
];
